### ISSUE TITLE
Anordnung der Blogeinträge passt nicht

### ISSUE THREAD

**Issue by matthias-mueller** [pikobytes/smartrain-website#10]
s. Screenshot: Hier spult es offenbar die Anordnung durcheinander. Ursache unbekannt. (Liegt das vlt. an unterschiedlichen Bildgrößen?

https://smart-rain.de/blogs.html

![bildschirmfoto von 2018-11-06 09-56-04](https://user-images.githubusercontent.com/4289185/48053218-6598c200-e1aa-11e8-886d-f42245315b54.png)

**Comment by PIEKAR** [comment]
Das ist  mir auch schon aufgefallen... das ist auch nicht schön ;-)
