### ISSUE TITLE
PNG-Grafiken ermöglichen

### ISSUE THREAD

**Issue by matthias-mueller** [pikobytes/smartrain-website#5]
Ich würde für Blogposts auch gern PNGs hochladen, die werden aber zur Zeit nicht erkannt.

**Comment by matthias-mueller** [comment]
Also die Lösung fände ich voll in Ordnung

**Comment by PIEKAR** [comment]
Ich auch

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Matthias Müller <notifications@github.com>
Gesendet: Donnerstag, 23. August 2018 14:51
An: pikobytes/smartrain-website
Cc: Subscribed
Betreff: Re: [pikobytes/smartrain-website] PNG-Grafiken ermöglichen (#5)


Also die Lösung fände ich voll in Ordnung

-

**Comment by jacmendt** [comment]
Wird mit dem nächsten Commits geschlossen. Danach können Banner- und Thumb-Bilder explizit definiert werden, z.B.:

```
layout: post
title: SmartRain kooperiert mit MAtchUP
image_banner: smart_rain_header_banner.jpg
image_thumb: smart_rain_header_thumb.jpg
author: Pierre Karrasch
```

Die Bilder müssen sich allerdings weiterhin im Verzeichnis `assets/images/posts/` befinden.
